spring:
  application:
    name: AllSpark-Official-Website
  # 默认 dev 环境
  profiles:
    active: dev
  # session 配置
  session:
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/allsaprk?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: 0721
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

server:
  address: 0.0.0.0
  port: 8721
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

knife4j:
  enable: true
  openapi:
    title: 接口文档
    description: "接口测试"
    email: gilgamesh@qq.com
    concat:
    url: https://github.com/fantasy-lotus/
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name:  lotus
        api-rule: package
        api-rule-resources:
          - com.allspark.allsparkofficialwebsite.controller

logging:
  level:
    root: info