spring:
  application:
    name: AllSpark-Official-Website
  config:
    activate:
      on-profile: prod
  session:
    # 30 天过期
    timeout: 2592000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/allsaprk?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: allspark
    password: allspark520
    type: com.alibaba.druid.pool.DruidDataSource

server:
  address: 0.0.0.0
  port: 8721
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

mybatis-plus:
  configuration:
    log-impl: ''

knife4j:
  basic:
    enable: true
    username: lotus
    password: allspark520

storage:
  image:
    path: static/images/
  json:
    path: static/json/